### ISSUE TITLE
sollumz issue

### ISSUE THREAD

**Issue by Mhee-Zoo** [Sollumz/Sollumz#1039]
please help this case. please.....

Failed adding normal.sps to skull_geom because : 
 Traceback (most recent call last):
  File "C:\Users\7YAB\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Sollumz-main\ydr\operators.py", line 165, in run
    bl_idname = "sollumz.create_light"
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\7YAB\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Sollumz-main\ydr\operators.py", line 143, in create_material
    bl_idname = "sollumz.converttodrawablemodel"
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\7YAB\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 763, in create_shader
    multiply_color.operation = "MULTIPLY"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\7YAB\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\Sollumz-main\ydr\shader_materials.py", line 625, in create_basic_shader_nodes
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

**Comment by alexguirre** [comment]
Update Sollumz to latest version.

**Comment by Mhee-Zoo** [comment]
im Update latest version already but still can't

**Comment by Mhee-Zoo** [comment]
thank you now can use
