### ISSUE TITLE
Error importing: prop_pot_plant_03b.yft.xml

### ISSUE THREAD

**Issue by fhsjxk** [Sollumz/Sollumz#1047]
### 🔍 Issue Description

Error importing: X:\Users\qwert\Desktop\BugerShot\assets\full\levels\gta5\_citye\indust_02\drawables\id2_21_c_strm_1\prop_pot_plant_03b.yft.xml 

### 🛠️ Sollumz Version(s)

2.6.1

### 🖥️ Blender Version(s)

4.0

### 🧩 Area

Fragments

### 🔄 Reproduction steps

Import prop_pot_plant_03b.yft.xml

### ⚠️ Current Result

Error importing: X:\Users\qwert\Desktop\BugerShot\assets\full\levels\gta5\_citye\indust_02\drawables\id2_21_c_strm_1\prop_pot_plant_03b.yft.xml 
 Traceback (most recent call last):
  File "C:\Users\qwert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\sollumz_operators.py", line 103, in execute_timed
    import_yft(filepath)
  File "C:\Users\qwert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftimport.py", line 48, in import_yft
    return create_fragment_obj(yft_xml, non_hi_filepath, name,
  File "C:\Users\qwert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz\yft\yftimport.py", line 104, in create_fragment_obj
    assert a.unknown_48 == b.unknown_48, "gravity_factor different in damaged archetype. Open an issue!"
AssertionError: gravity_factor different in damaged archetype. Open an issue!

**Comment by alexguirre** [comment]
Huh, that prop seems to be missing the physics archetype for the damaged model, the `<Archetype2>` tag in the XML.

**Comment by alexguirre** [comment]
> Huh, that prop seems to be missing the physics archetype for the damaged model, the `<Archetype2>` tag in the XML.

Turns out, the damaged model of `prop_pot_plant_03b.yft` is broken. `prop_streetlight_12b.yft` has a similar issue too. Thought there was a reason for it to be missing the damaged physics archetype, but no, just a bad asset.

Gonna allow to import them, but they will stay broken after export. Need to manually fix them, I guess by adding damaged collisions.

This is how the vanilla files behave:

https://github.com/user-attachments/assets/592f240e-2173-4059-8d1c-f349026da60f

https://github.com/user-attachments/assets/63531b8f-a5e8-40ba-867f-5a05ee420722

What they should look like:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/1336e5b3-af93-49ad-a247-1ea582f927c1" />
