### ISSUE TITLE
Clothing part issue: IndexError: index 48 is out of bounds for axis 0 with size 24

### ISSUE THREAD

**Issue by MoravianLion** [Sollumz/Sollumz#759]
I imported some clothing parts and accessories for Franklin from the base game and one prop specifically gave me the error below.

I downloaded the latest Sollumz today, error persisted.

The model in question is called "uppr_025_u" and the error happens with and without the external skeleton being used.

x64v.rpf\models\cdimages\streamedpeds_players.rpf\player_one

I also noticed, for the first time, that with this same prop name, there's also .yld file. This might be related? I never worked with GTA clothing, so I have no clue here.

`Error importing: E:\Radek\Zábava\YT\Projects\Blender\lamar_roasts_franklin_orig\xmls\player_one\props\uppr_025_u.ydd.xml 
 Traceback (most recent call last):
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\sollumz_operators.py", line 95, in execute_timed
    import_ydd(filepath)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydd\yddimport.py", line 24, in import_ydd
    return create_ydd_obj_ext_skel(ydd_xml, filepath, skel_yft)
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydd\yddimport.py", line 66, in create_ydd_obj_ext_skel
    drawable_obj = create_drawable_obj(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 60, in create_drawable_obj
    model_objs = create_rigged_drawable_models(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\ydrimport.py", line 79, in create_rigged_drawable_models
    model_datas = get_model_data(
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\model_data.py", line 32, in get_model_data
    mesh_data_lods={
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\model_data.py", line 33, in <dictcomp>
    lod_level: mesh_data_from_xml(model_xml) for lod_level, model_xml in model_lods.items()
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\model_data.py", line 230, in mesh_data_from_xml
    vert_arr=get_model_joined_vert_arr(geoms),
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\model_data.py", line 263, in get_model_joined_vert_arr
    apply_bone_ids(vert_arr, np.array(geom.bone_ids))
  File "C:\Users\MoravianLion\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\Sollumz-main\ydr\model_data.py", line 294, in apply_bone_ids
    vert_arr["BlendIndices"] = bone_ids[vert_arr["BlendIndices"]]
IndexError: index 48 is out of bounds for axis 0 with size 24

`

**Comment by alexguirre** [comment]
> there's also .yld file

Probably the issue here, .yld's define cloth physics and are not supported by Sollumz yet.
