### ISSUE TITLE
Exporting with no collision material gives an exception error

### ISSUE THREAD

**Issue by krzysiula3000** [Sollumz/Sollumz#962]
both embedded and ybn
and when the col has a shader material

**Comment by Rigonkmalk** [comment]
When the col has a shader material / without shader material /embbeded or unembedded :

```
Error exporting: E:\Documents\gta5\Mes projets\SOZ\TESTING\Assets_Socialite\Sollumz\contourporte.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\rigon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sollumz\sollumz_operators.py", line 208, in execute_timed
    success = export_ydr(obj, filepath)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rigon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sollumz\ydr\ydrexport.py", line 68, in export_ydr
    drawable_xml = create_drawable_xml(drawable_obj, apply_transforms=export_settings.apply_transforms)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rigon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sollumz\ydr\ydrexport.py", line 116, in create_drawable_xml
    create_embedded_collision_xmls(drawable_obj, drawable_xml)
  File "C:\Users\rigon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sollumz\ydr\ydrexport.py", line 898, in create_embedded_collision_xmls
    bound_xml = create_composite_xml(bound_obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rigon\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sollumz\ybn\ybnexport.py", line 80, in create_composite_xml
    cg /= volume
ZeroDivisionError: Vector division: divide by zero error
```
